name: Run Automated Test 🚀🚀

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  automation-test:
    runs-on: [self-hosted, robot-selenium-py]
    steps:
      - uses: actions/checkout@v3
      - name: Installing automation requirements 
        run: pip3 install -r requirements.txt
      - name: Running Automation Test 
        id: test
        run: |
          python3 -m robot test-cases